config/routes.rb
Rails.application.routes.draw do
  devise_for :staffs, controllers: {
    sessions: 'staffs/sessions'
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  namespace :admin do
    resources :welcome, only: :index
    resources :users
  end

  resources :welcome, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  has_and_belongs_to_many :staffs, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/staff.rb
class Staff < ApplicationRecord
  rolify
  before_create :assign_default_info
  after_create :assign_default_role

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  enum status: { disable: 0, enable: 1 }

  private

  def assign_default_info
    self.status = :enable if self.status.blank?
  end

  def assign_default_role
    self.add_role :staff if self.roles.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  before_create :assign_default_info
  after_create :assign_default_role

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  enum status: { disable: 0, enable: 1 }
  enum rank: { dongsan: 0, namsan: 1, chunggaesan: 2 }

  private

  def assign_default_info
    self.status = :enable if self.status.blank?
    self.rank = :dongsan if self.rank.blank?
  end

  def assign_default_role
    # 회원가입 시, 일반 회원 권한 부여 - 단순 조회만 가능
    self.add_role :normal if self.roles.blank?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_staff!

  layout 'admin_application'

  def index
    @users = User.all
  end
end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < ApplicationController
  before_action :authenticate_staff!

  layout 'admin_application'

  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection

  protected

  def after_sign_in_path_for(resource)
    if staff_signed_in?
      admin_welcome_index_path
    elsif user_signed_in?
      welcome_index_path
    end
  end
end

app/controllers/staffs/sessions_controller.rb
# frozen_string_literal: true

class Staffs::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def new
    super
  end

  def create
    super
  end

  def edit
    super
  end

  def update
    super
  end

  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :display_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :display_name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/index.html.erb
<h1>회원 관리</h1>

<table class="table">
  <thead>
  <tr>
    <th scope="col">ID</th>
    <th scope="col">email</th>
    <th scope="col">이름</th>
    <th scope="col">닉네임</th>
    <th scope="col">등급</th>
    <th scope="col">불참 횟수</th>
    <th scope="col">불참 횟수(연속)</th>
    <th scope="col">가입일</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <th scope="row"><%= user.id %></th>
      <th scope="row"><%= user.email %></th>
      <th scope="row"><%= user.name %></th>
      <th scope="row"><%= user.display_name %></th>
      <th scope="row"><%= user.rank %></th>
      <th scope="row"><%= user.absence_cnt %></th>
      <th scope="row"><%= user.successive_absence_cnt %></th>
      <th scope="row"><%= user.created_at %></th>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/welcome/index.html.erb
hello staff!

app/views/layouts/_admin_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to '동산 ADMIN', admin_welcome_index_path, class: 'navbar-brand mx-4' %>
  <!--  <a class="navbar-brand mx-4" href="#">동산</a>-->
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse flex-row-reverse bd-highlight" id="navbarNav">
    <ul class="navbar-nav">
      <% if staff_signed_in? %>
        <li class="nav-item active">
          <%= link_to '로그아웃', '', class: 'logout-btn nav-link', remote: true %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to '로그인', new_staff_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% end %>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Services</a>
      </li>
      <li class="nav-item">
        <%= link_to '질문하기(오카방)', 'https://open.kakao.com/o/szEp4P5e', class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to '동산', welcome_index_path, class: 'navbar-brand mx-4' %>
  <!--  <a class="navbar-brand mx-4" href="#">동산</a>-->
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse flex-row-reverse bd-highlight" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to '로그아웃', '', class: 'logout-btn nav-link', remote: true %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to '로그인', new_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% end %>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Services</a>
      </li>
      <li class="nav-item">
        <%= link_to '질문하기(오카방)', 'https://open.kakao.com/o/szEp4P5e', class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

<script>
  $(function () {
    const navBarVisible = $('#navbarNav').is(':visible');
    if (!navBarVisible) {
      $('a').addClass('mx-3');
    } else {
      $('a').removeClass('mx-3');
    }
  });

  $('.logout-btn').click(function (e) {
    e.preventDefault();
    $.ajax({
      url: "/users/sign_out",
      method: "DELETE",
      dataType: 'json',
      success: function (data) {
        location.reload();
      },
      error: function(xhr, textStatus, errorThrown) {
        console.log(xhr, textStatus, errorThrown);
      }
    })
  });
</script>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta charset="UTF-8">
  <title>어드민 :동산</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- header icon -->
  <link rel="shortcut icon" type="image/x-icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/800px-Apple_logo_black.svg.png">

  <!-- Bootstrap 5 CDN -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

  <!-- Jquery CDN -->
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

  <!-- custom css -->
  <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>

  <!-- 나눔 고딕 폰트 -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap" rel="stylesheet">
</head>

<body>
<!-- 로그인, 회원가입 화면에서는 nav bar 노출 X -->
<% unless ['Staffs::SessionsController', 'Staffs::RegistrationsController'].include?(controller.class.to_s) %>
  <%= render 'layouts/admin_navbar' %>
<% end %>

<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="UTF-8">
    <title>동국대학교 등산 동아리 :동산</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- header icon -->
    <link rel="shortcut icon" type="image/x-icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/800px-Apple_logo_black.svg.png">

    <!-- Bootstrap 5 CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <!-- Jquery CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <!-- custom css -->
    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>

    <!-- 나눔 고딕 폰트 -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap" rel="stylesheet">
  </head>

  <body>
    <!-- 로그인, 회원가입 화면에서는 nav bar 노출 X -->
    <% unless ['Users::SessionsController', 'Users::RegistrationsController'].include?(controller.class.to_s) %>
      <%= render 'layouts/navbar' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/staffs/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/staffs/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<!-- 동아리 대표 사진 -->
<div class="main-img">
  <%= image_tag "p_main3.png", class: 'main-img-src' %>
  <div class="main-img-text hidden">
    <h1>반가워요!</h1>
  </div>
</div>

<!-- 동아리 간단소개 글 -->
<div class="main-section-1">
  <h1 class="main-section-1-title">동아리 소개</h1>
  <p class="main-section-1-paragraph">
    이것은 동아리 소개 글입니다. 동산은 영국에서 시작하여 동남아를 거쳐서 미국에 도달하기까지 많은 시간이 들지 않았는데 한국에 들어오면서 재미난 여행을 저희는 다녀왔습니다.
    안녕하세요. 반갑습니다. 잘지내세요?
    test 동아리 소개 글.
    테스트 동아리 소개 글입니다. 추가 작성을 해주시길 바랍니다.
  </p>
</div>

<div class="main-section-2">
  <h1 class="main-section-2-title">지원하러 가기</h1>
  <%= link_to 'Go! →', 'https://forms.gle/rrucgTcK2CYEgmbW6', class: 'apply-btn' %>
</div>

<script>
  $(document).bind('contextmenu', function () {
    return false;
  })

  $(document).bind('selectstart', function () {
    return false;
  });

  $(document).bind('dragstart', function () {
    return false;
  });

  $('.main-img').click(function () {
    const $mainImageSrc = $('.main-img-src');
    // 투명도가 설정됐다면 원래대로 1로 변경
    if ($mainImageSrc.css('opacity') == 0.3) {
      // 원래대로 투명도 1로 변경
      $mainImageSrc.animate({
        opacity: '1'
      }, 200, function () {
        $('.main-img-text').fadeOut(50, function () {
          $('.main-img-text').addClass('hidden');
        });
      });
    } else {
      $mainImageSrc.animate({
        opacity: '0.3'
      }, 300, function () {
        $('.main-img-text').fadeIn(400, function () {
          $('.main-img-text').removeClass('hidden');
        });
      });
    }
  });
</script>